### ISSUE TITLE
Missing features

### ISSUE THREAD

**Issue by faierbol** [marketplacekit/marketplacekit#1]
Hi there.
First of all i want to say congrats regarding this beautiful product.
Can you please update the code because some features are missing, like the error Class Modules\Panel\Http\Controllers\PricingModelsController does not exist and Homepage settings.

Kind regards

**Comment by marketplacekit** [comment]
Hello,

Thanks for your comment!

I've removed the missing routes/files now. Hope that helps.

Commit 9ba4362f34369a9dfa08872893ff8571e944c9d8

**Comment by faierbol** [comment]
Thanks a lot and keep up the good work.

**Comment by faierbol** [comment]
By any chance, can you please push the code from https://panel.marketplacekit.com/ demo :)

**Comment by dammyammy** [comment]
@faierbol To preview the panel simply add the following

`php
Route::get('/cp', function () {
    if(env('DEMO_PANEL')) {
        \Auth::loginUsingId(1, true);
        return redirect("/panel");
    }
});
`

and set in your .env 

`
DEMO_PANEL=true
`

Great Job so far guys, would really be open to contributing if you need contributors. Think this can be huge.

**Comment by faierbol** [comment]
@dammyammy Thank you, but i asked @marketplacekit if he can push the code from https://panel.marketplacekit.com/ because the actual code is incomplete.

**Comment by marketplacekit** [comment]
Hello, sorry for the delay, pushed the latest version now - with stripe and the different pricing models. hope it helps :)
