### ISSUE TITLE
Issues with listing photo upload

### ISSUE THREAD

**Issue by tcunningham07** [marketplacekit/marketplacekit#15]
When trying to create a new listing, it appears that the photos do not successfully upload.

I can see that they are atttempted to be loaded from `http://.../storage/images/2018/08/05/d61238710702145baebea318161c22b1.jpg`
but the appropriate folders/filename required does not appear to be written to the expected location on the server.

**Comment by inputchip** [comment]
`php artisan storage:link`

**Comment by marketplacekit** [comment]
Thanks @inputchip added to the readme too now https://github.com/marketplacekit/marketplacekit/commit/4cc9b7956ca8f789422ca10b2bf5f0d7ccb44bcd
