### ISSUE TITLE
Logo cannot be deleted to allow text only title

### ISSUE THREAD

**Issue by tcunningham07** [marketplacekit/marketplacekit#17]
After uploading a logo image, the image cannot be deleted to restore the 'text only' site title in the top left corner. A new logo can be uploaded to overwrite but I cannot find a way to delete the logo altogether and just use text

**Comment by marketplacekit** [comment]
The latest update now let's you delete the logo https://github.com/marketplacekit/marketplacekit/commit/c2f0ebd972e0daaaa6d5f77a4025f04b8b169f46

**Comment by tcunningham07** [comment]
Fixed! Keep up the good work.
