### ISSUE TITLE
db seed error

### ISSUE THREAD

**Issue by salimbenfarhat** [marketplacekit/marketplacekit#18]
When i run 
`php artisan db:seed`
I get this error
`Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1305 FUNCTION marketplace.ST_GeomFromText does not exist`
How to fix it please ?

**Comment by salimbenfarhat** [comment]
Exception trace:

`1   PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1305 FUNCTION marketplace.ST_GeomFromText does not exist")
      /home/ubuntu/workspace/marketplacekit/vendor/laravel/framework/src/Illuminate/Database/Connection.php:452`

`2   PDO::prepare("insert into `listings` (`blurb`, `category_id`, `city`, `country`, `created_at`, `currency`, `deleted_at`, `description`, `id`, `is_admin_verified`, `is_disabled`, `is_published`, `key`, `lat`, `lng`, `locale`, `location`, `max_duration`, `max_units`, `meta`, `min_duration`, `min_units`, `photo`, `photos`, `price`, `price_per_unit_display`, `pricing_model_id`, `pricing_models`, `quantity`, `seller_type`, `session_duration`, `spotlight`, `staff_pick`, `stock`, `tags`, `tags_string`, `timeslots`, `title`, `unit`, `units_in_product_display`, `updated_at`, `user_id`, `variant_options`, `vendor`, `views_count`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ST_GeomFromText('POINT(-0.10213410 51.509865)'), ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)")
      /home/ubuntu/workspace/marketplacekit/vendor/laravel/framework/src/Illuminate/Database/Connection.php:452`

**Comment by marketplacekit** [comment]
It sounds like the spatial functions might be missing from the MySQL server.

Could you please use MySQL 5.7.7 or greater? It includes the new Geo-Spatial features.

**Comment by salimbenfarhat** [comment]
Thank you i've upgraded mysql version and now its fixed.
