### ISSUE TITLE
Lots of potential

### ISSUE THREAD

**Issue by viarocket** [marketplacekit/marketplacekit#2]
I love this repo. It has a lot of potential to be a great product. 

@marketplacekit , do you plan to have regular improvements to this app? Any roadmap you could share? 

Well done! Love this!

**Comment by marketplacekit** [comment]
Thanks! Pushed a roadmap now.

https://github.com/marketplacekit/marketplacekit/blob/master/roadmap.md

If you have any suggestions let me know :)
