### ISSUE TITLE
SQLSTATE[42000]: Syntax error or access violation

### ISSUE THREAD

**Issue by robkerry** [marketplacekit/marketplacekit#20]
I get the following error on a fresh install:

> LOG.error: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '>'$."price"') as aggregate from `listings` where `listings`.`deleted_at` is null' at line 1 (SQL: select min(`meta`->'$."price"') as aggregate from `listings` where `listings`.`deleted_at` is null) {"userId":1,"email":"admin@example.com","exception":{"errorInfo":["42000",1064,"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '>'$.\"price\"') as aggregate from `listings` where `listings`.`deleted_at` is null' at line 1"]}}

Seems to be an issue with `app/Http/Controllers/BrowseController.php`, maybe line 85

**Comment by marketplacekit** [comment]
Hello,

Would you be able to use MySQL 5.7.7+ instead?

Laravel doesn't support JSON Where clauses in MariaDB yet. There's a package that adds MariaDB JSON support that might help, though I've never tried it:
https://github.com/ybr-nx/laravel-mariadb

**Comment by robkerry** [comment]
Ah, that makes sense - I couldn't find an error in the code. Thanks for your time and hard work on this project - I'll aim to contribute once I've looked over the code and got it running :)

**Comment by hosamof** [comment]
how to fix it in mysql 5.6

**Comment by Ezyweb-uk** [comment]
> Laravel doesn't support JSON Where clauses in MariaDB yet. There's a package that adds MariaDB JSON support that might help, though I've never tried it:
> https://github.com/ybr-nx/laravel-mariadb

Seems to work for me. Thanks for the tip!
