### ISSUE TITLE
Cannot access admin page

### ISSUE THREAD

**Issue by olubiyi80** [marketplacekit/marketplacekit#22]
When I tried accessing, localhost:8000/panel, it reroutes back to home page. How can I access the admin panel.

Thanks @marketplacekit @dammyammy

**Comment by inputchip** [comment]
Login as per the `readme.md`. 
Username: admin@example.com
Password: changme

**Comment by olubiyi80** [comment]
Ok it works now, Had to changed my user ID.

**Comment by EmmaTheGr8est** [comment]
@olubiyi80 please how did you change your user ID, i'm also facing the same issue

**Comment by olubiyi80** [comment]
I changed it from the database, on the users table. Change the id to 1, and try to log in again.

**Comment by tanzaniatech** [comment]
Did this solution work for you.? because to me its not

**Comment by shahidkarimi** [comment]
Nothing worked for me. Please help

**Comment by escit** [comment]
affter login, you use url: [site]/panel

**Comment by shahidkarimi** [comment]
That doesn't work. It redirects back to the home page @escit

**Comment by shahidkarimi** [comment]
I have to do this mannually. All I needed to assign roles and permissions manually. I love myself.

**Comment by mswap** [comment]
solution given on page  works
https://github.com/marketplacekit/marketplacekit/issues/29.
