### ISSUE TITLE
Class 'Jralph\Twig\Markdown\Extension' not found

### ISSUE THREAD

**Issue by inputchip** [marketplacekit/marketplacekit#28]
Symfony\Component\Debug\Exception\FatalThrowableError thrown with message "Class 'Jralph\Twig\Markdown\Extension' not found"

Stacktrace:
#0 Symfony\Component\Debug\Exception\FatalThrowableError in C:\laragon\www\marketplacekit\config\twigbridge.php:120

**Comment by marketplacekit** [comment]
Could you try and run `composer update` to download the new dependencies?
