### ISSUE TITLE
Cannot access admin panel after updating.

### ISSUE THREAD

**Issue by olubiyi80** [marketplacekit/marketplacekit#29]
@marketplacekit admin panel is not available after updating,

Please what do I need to do?

And the following default pages are not longer showing on homepage.

Thanks.

**Comment by inputchip** [comment]
Can you please provide more info. Are you getting any errors? Did you check the logfile?

**Comment by david-saint** [comment]
Yeah I'm getting the same issue now. There's nothing in the log files. I'm still troubleshooting anyway. I would come back if I figure it out.

**Comment by olubiyi80** [comment]
Thank you. @david-saint.

It worked!

**Comment by shahidkarimi** [comment]
@david-saint when I do this i got:
` Spatie\Permission\Exceptions\PermissionDoesNotExist  : There is no permission named `edit listing` for guard `web`.`

**Comment by mswap** [comment]
> So I fixed it. I'm not really sure what caused it, because I was contracted to fix the issue.
> At first, I thought it was an issue with the middlewares but after a couple minutes troubleshooting I figured out it was actually the db:seed process that failed somehow.
> 
> So I just ran `php artisan migrate:refresh`
> then make sure **BCMath** is installed `sudo apt install php7.2-bcmath`
> then run `php artisan db:seed`

This worked for me.
