### ISSUE TITLE
Admin login page URL

### ISSUE THREAD

**Issue by VadymChadyuk** [marketplacekit/marketplacekit#39]
Hi!
Please let me know which page is for admin's login. I have just intalled Marketplacekit and I have no idea how to get in.
Thank you.

**Comment by timeholes** [comment]
Hi! Admins log in the same way like regular users, via `example.com/login` and then you can open control panel at `example.com/panel` (accessible by clicking 'setttings' icon in the header).

**Comment by VadymChadyuk** [comment]
Thanks for your prompt response. It seems like we missed the password change during installation and now login page does not allow to fill-in "admin" since it's not email address. Please advise.
Thank you.

**Comment by timeholes** [comment]
Yes, I've just dealt with all the same problems 2 days ago, the default admin login is `admin@example.com`, password `changeme`, as seen here https://github.com/marketplacekit/marketplacekit/blob/master/database/seeds/UsersTableSeeder.php
After first login you can add admin role to another user, maybe you can change email as well, but I just decided to use another user as admin.

**Comment by VadymChadyuk** [comment]
Your advice worked, the problem solved. Thank you.
