### ISSUE TITLE
Issue when creating a "Book a Date" Pricing Model

### ISSUE THREAD

**Issue by calebdomingo** [marketplacekit/marketplacekit#5]
When creating a "Book a Date" Pricing model, it throws this error:

<img width="1235" alt="screen shot 2018-07-17 at 11 03 10 am" src="https://user-images.githubusercontent.com/21233695/42794460-7e81a86e-89b1-11e8-910a-90ee99afc580.png">

Hope this helps thanks

**Comment by marketplacekit** [comment]
For reference, fixed in https://github.com/marketplacekit/marketplacekit/commit/2a777004d12742d7dc3e4c4d1982a477acbaab7b

Thanks
