### ISSUE TITLE
Not showing buy button to post

### ISSUE THREAD

**Issue by niteshn99** [marketplacekit/marketplacekit#54]
Great work guys. Its awesome to have something like this. Recently, I installed it and exploring around to see functionality. I noticed that instead of Buy button I am getting contact seller button and I am not able to figure out how to solve this. Please suggest me if I am missing some setting.
![image](https://user-images.githubusercontent.com/6436785/49357881-b1ca1a00-f6f6-11e8-8c2a-8c94754c6b6f.png)

**Comment by niteshn99** [comment]
After exploring a while I came across payment setting in user profile where user need to provide bank details. I am suspecting this setting may enable buy button on listing. Some one please confirm. Another thing is that I am not able to add my banking details as India is not in provided country list. Does someone knows how to add country to available list.

**Comment by niteshn99** [comment]
Or is there any ways to add payment gateways other than paypal?

**Comment by marketplacekit** [comment]
Hi Nitesh,

Thanks for your email.

Yes, the buy buttons appear only when you add your bank account/paypal
account. Bank account is only available for countries supported by stripe.

We're based in the UK, so stripe is enough for us but we'll make a more
flexible payment system as soon as we can. Which payment system do you need
to integrate?

There's a list of files you need to change to add a new payment processor.
I don't know if it'll help:
https://marketplacekit.com/adding-a-new-payment-processor/

Thanks,
Kevin

**Comment by niteshn99** [comment]
Hi Kevin,

We are based in India and unfortunately, India is not listed in stripe country list and we are not sure about implementing paypal yet. 

There are few potential payment gateways such as payumoney (https://www.payumoney.com/) and razorpay (https://razorpay.com/).

As mentioned on knowledge base page (link provided by you in above reply), I had a look at BankAccountController and CheckoutController. However, still struggling to figure out how and what code do I need to add in existing code to list Indian payment gateways in options along with stripe and paypal.

Please let me know if you come across any existing implementation, thus I can take it as a reference for my starting point.

Thanks,
Nitesh

**Comment by niteshn99** [comment]
Its not an issue, just lack of desired payment gateways. Hence closing this issue.
