### ISSUE TITLE
The app seems to be only in English

### ISSUE THREAD

**Issue by nzurita** [marketplacekit/marketplacekit#63]
I see literals are written in English in views, aren't they? I mean, the app is not translatable...

Do you plan to add localization ability at some point? I'm more used to Symfony than Laravel, but in case localizations are similar, I can migrate views to translatable literals, as I need them to be in another language. Would you accept some collaboration with that (i.e. pull request)?

**Comment by nzurita** [comment]
Am I missing something? Setting _APP_LOCALE_ to `es` in `.env` file doesn't update `{{current_locale()}}` in views, it still shows `en` (it's not a cache issue).

    APP_LOCALE=es

**Comment by marketplacekit** [comment]
It's overwritten by the setting saved in the admin.

You can use _Admin panel > Settings_ to change the default language.
