### ISSUE TITLE
Failed to reconnect paypal account

### ISSUE THREAD

**Issue by niteshn99** [marketplacekit/marketplacekit#65]
While doing sandbox test I connected user account with sandbox paypal account. After changing paypal from sandbox to live, I tried to reconnect to live account but paypal always ends up with error saying invalid scope. Have anyone faced this issue earlier. Any help will be appreciated.

![image](https://user-images.githubusercontent.com/6436785/50722465-7788d980-10f5-11e9-8abc-ec487b9603d6.png)

**Comment by marketplacekit** [comment]
It seems a lot of people are having this issue.

In the paypal developer settings screen, could you please scroll down to "LIVE APP SETTINGS". 
Then, in the "Log In with PayPal section" please make sure the Email address is selected.

![image](https://user-images.githubusercontent.com/38989970/50724440-6fc13900-10e5-11e9-842c-2d37eba8bd39.png)
