### ISSUE TITLE
Missing translation in the list.twig

### ISSUE THREAD

**Issue by obikenoby** [marketplacekit/marketplacekit#68]
e.g. "4 days ago" doesn't translated because instance of translator has set locale to 'en' instead current locale.

I apprechiate some advice how to fix this issue.

**Comment by marketplacekit** [comment]
Could you try and add 

`\Carbon\Carbon::setLocale(current_locale());` in `app/Providers/AppServiceProvider` ?

e.g.
```
class AppServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        \Carbon\Carbon::setLocale(current_locale());
        ...
```

**Comment by obikenoby** [comment]
It works, thank you.
