### ISSUE TITLE
Error when add new category

### ISSUE THREAD

**Issue by duluong** [marketplacekit/marketplacekit#7]
I think there might be a bug in the CategoriesController.php controller.
In save_languages function.

public function save_languages()
    {
        $categories = Category::orderBy('order', 'ASC')->get();
        //save_language_file('categories', $categories->pluck('name'));   <- this step was error. 
        // I think the second parameter should be changed to array as bellow. 
        save_language_file('categories', $categories->pluck('name')->toArray());
    }

**Comment by marketplacekit** [comment]
#8
