### ISSUE TITLE
A "edit listing" permission already exist for guard 'web' 

### ISSUE THREAD

**Issue by Chernyackoff** [marketplacekit/marketplacekit#76]
The 'db:seed' comand returns the error (A "edit listing" permission already exist for guard 'web' ).
I have already tried 'php artisan cache:clear', 'php artisan cache:forget' but it didn't help.

**Comment by Chernyackoff** [comment]
Sorry. Found out

**Comment by rajm** [comment]
what did you do to fix it?

**Comment by Chernyackoff** [comment]
I have deleted the db and started from the scratch. Delete marketplacekit and start it again. Also make surrthat you have all extensions!!!
