### ISSUE TITLE
Compatibility MariaDB

### ISSUE THREAD

**Issue by lzomedia** [marketplacekit/marketplacekit#80]
So I'm trying to run your project on one of my servers with the following 

> `MariaDB [(none)]> SHOW VARIABLES LIKE "%version%";
> +-------------------------+---------------------------------+
> | Variable_name           | Value                           |
> +-------------------------+---------------------------------+
> | innodb_version          | 5.7.25                          |
> | protocol_version        | 10                              |
> | slave_type_conversions  |                                 |
> | version                 | 10.2.22-MariaDB                 |
> | version_comment         | MariaDB Server                  |
> | version_compile_machine | x86_64                          |
> | version_compile_os      | Linux                           |
> | version_malloc_library  | system                          |
> | version_ssl_library     | OpenSSL 1.0.1e-fips 11 Feb 2013 |
> | wsrep_patch_version     | wsrep_25.24                     |
> +-------------------------+---------------------------------+

10 rows in set (0.00 sec)
`

but the thing is I get 

`SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '>'$."price"') as aggregate from `listings` where `listings`.`deleted_at` is null' at line 1 (SQL: select min(`meta`->'$."price"') as aggregate from `listings` where `listings`.`deleted_at` is null)`

i guess is not compatible with MariaDB even if version 10.2.22 is compatible with mysql 5.7.7

any ideea how can i fix this or do I real need mysql insted mariadb

**Comment by LunarDevelopment** [comment]
I had this issue and found that short of re-writing a lot of db query syntax in this repo, it was a lot easier to swap to MySQL from MariaDB. 

The root of the issue is that MySQL supports "json_column->key" syntax, MariaDB does not.  

p.s. there are MySQL to MariaDB laravel libraries that translate DB queries into MariaDB syntax knocking around, but I had no success using them.

**Comment by lzomedia** [comment]
Yeah I was thinking the same thing, anyway good project but I decided to stick to my own codebase till the end
