### ISSUE TITLE
"array_unique() expects parameter 1 to be array, object given"

### ISSUE THREAD

**Issue by jesusave** [marketplacekit/marketplacekit#9]
project/app/Support/helpers.php

ErrorException 
…/app/Support/helpers.php 144

    $selected_locale = 'en';
    $strings = array_unique($strings);
    $strings = array_filter($strings);
    foreach($strings as $string) {
        $translation_row = Translation::where('locale', $selected_locale)
            ->where('group', '_json')
            ->where('key', $string)
            ->first();
        if(!$translation_row) {
            $translation_row = new Translation();
            $translation_row->key = $string;
            $translation_row->locale = $selected_locale;
            $translation_row->group = '_json';
            $translation_row->value = null;
            $translation_row->save();
        }
    }

**Comment by marketplacekit** [comment]
fixed in https://github.com/marketplacekit/marketplacekit/commit/4cc9b7956ca8f789422ca10b2bf5f0d7ccb44bcd
