### ISSUE TITLE
a lot of bugs

### ISSUE THREAD

**Issue by scriptfarm** [marketplacekit/marketplacekit#92]
nice script, but unfortunately a lot of bugs.

Example : panel/pages 
delete Content pages does not work, no link in the remove button.

Example : panel/fields/create
Adding new field, no formular check in Field "Position".
You can enter a letter then cames a error message.
..."Incorrect integer value: 'XXX' for column 'position'...

Example : panel/roles/1/edit
Allow user to select this role on registration
Does not work when registering.

Example : create/kopKVQbNDw/edit
After Publish a Listing you can not anymore remove Variation, and Shipping Fees.

In my Test Market
https://test-market-1.marketplacekit.com/create
if I want to post listing, then comes  "Error 500 - Internal Server Error".

I could say ten more. in Payment, Admin and User Panel..
Almost all versions, but mostly : Demo and Self Hosting (v1.0.4, v1.0.7).

Thanks Rene

**Comment by marketplacekit** [comment]
Hello,

Thanks for your feedback. The first three are fixed in dev-master.

> After Publish a Listing you can not anymore remove Variation, and Shipping Fees.
There's a delete button next to shipping fees.
For variations, you can remove the variation from the input box.

> if I want to post listing, then comes "Error 500 - Internal Server Error".
It says your stripe account is not connected. Please connect it.
